---
title: "iamsilvia_capstone project"
format: html
editor: visual
---

## **Project Description**

## Load Packages

```{r}
library(tidyverse)
```

## Import Data

```{r}
library(readxl)
library(here)

raw_data_water <- read_xlsx(
  here::here("data/raw/JMP_WASH_HH_2025_by_country-2.xlsx"),
  sheet = "Water")

raw_data_san <- read_xlsx(
  here::here("data/raw/JMP_WASH_HH_2025_by_country-2.xlsx"),
  sheet = "Sanitation")

raw_data_hyg <- read_xlsx(
  here::here("data/raw/JMP_WASH_HH_2025_by_country-2.xlsx"),
  sheet = "Hygiene")

```

## Data Cleaning

#### Cleaning Water Dataset

```{r}
names(raw_data_water)

var_labels_water <- raw_data_water[2, ]

metadata_table_water <- tibble(
  variable_name = names(raw_data_water),
  variable_label = as.character(varname_long_water[1, ])
)

metadata_table_water$variable_label[1] <- "Country"

clean_data_water <- raw_data_water[-c(1,2), ]

#for (i in seq_along(metadata_table_water$variable_name)) {
#  attr(clean_data_water[[ metadata_table_water$variable_name[i] ]],
#      "label") <- metadata_table_water$varname_long_water[i]
#}

names(clean_data_water) <- metadata_table_water$variable_label

```

## 
